@echo off
taskkill /F /IM node.exe /T 2>nul
echo Starting Backend...
start /B node scripts/server.mjs > backend.log 2>&1
echo Starting Frontend Vite Dev Server...
start /B node ./node_modules/vite/bin/vite.js --host 127.0.0.1 > frontend.log 2>&1
echo Servers are starting in background...
