import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const audioDir = path.resolve('public/audio');
const outputFile = path.resolve('src/data/availableAudio.js');

function getDuration(filePath) {
    try {
        const cmd = `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${filePath}"`;
        const output = execSync(cmd).toString().trim();
        return parseFloat(output) || 0;
    } catch (e) {
        console.error(`Error getting duration for ${filePath}:`, e.message);
        return 0;
    }
}

try {
    const files = fs.readdirSync(audioDir)
        .filter(file => file.endsWith('.mp3'));

    const audioData = {};
    files.forEach(file => {
        const filePath = path.join(audioDir, file);
        audioData[file] = getDuration(filePath);
    });

    const content = `// This file is auto-generated by scripts/sync-audio.js
export const availableAudio = ${JSON.stringify(audioData, null, 2)};
`;

    fs.writeFileSync(outputFile, content);
    console.log(`Synced ${files.length} audio files with durations to ${outputFile}`);
} catch (err) {
    console.error('Error syncing audio files:', err.message);
    if (!fs.existsSync(outputFile)) {
        fs.writeFileSync(outputFile, 'export const availableAudio = {};\n');
    }
}
