
import fs from 'fs';
import path from 'path';

const audioDir = path.resolve('public/audio');
const outputFile = path.resolve('src/data/availableAudio.js');

try {
    const files = fs.readdirSync(audioDir)
        .filter(file => file.endsWith('.mp3'));

    const content = `// This file is auto-generated by scripts/sync-audio.js
export const availableAudio = ${JSON.stringify(files, null, 2)};
`;

    fs.writeFileSync(outputFile, content);
    console.log(`Synced ${files.length} audio files to ${outputFile}`);
} catch (err) {
    console.error('Error syncing audio files:', err.message);
    // Write an empty array if failed to prevent import errors
    if (!fs.existsSync(outputFile)) {
        fs.writeFileSync(outputFile, 'export const availableAudio = [];\n');
    }
}
